//! C11 `__atomic_*` operation wrappers for the TCC runtime library.
//!
//! Provides atomic read-modify-write operations implementing the complete set of
//! C11 atomic operations for 1, 2, 4, and 8-byte types.
//!
//! # C Equivalent
//!
//! `lib/stdatomic.c` (105 lines) — uses an `ATOMIC_GEN_OP` macro to generate
//! compare-and-swap (CAS) loop implementations of 13 atomic operations × 4 sizes
//! = 52 functions total, plus `__atomic_is_lock_free`.
//!
//! The original C implementation pattern:
//!
//! ```text
//! ATOMIC_GEN_OP(TYPE, MODE, NAME, OP, RET):
//!   TYPE __atomic_NAME_MODE(volatile void *atom, TYPE value, int memorder) {
//!       TYPE xchg, cmp;
//!       __atomic_load(atom, &cmp, __ATOMIC_RELAXED);
//!       do { xchg = OP; } while (!__atomic_compare_exchange(atom, &cmp, &xchg, ...));
//!       return RET;
//!   }
//! ```
//!
//! # Translation Strategy
//!
//! In Rust, the CAS loops in the C source map directly to `std::sync::atomic`
//! methods (`swap`, `fetch_add`, `fetch_sub`, `fetch_and`, `fetch_or`,
//! `fetch_xor`, `fetch_nand`) which compile to native hardware atomic
//! instructions on each supported architecture. The `*_fetch` variants
//! (returning the new value) compute the result from the `fetch_*` return
//! value (the old value) plus the operation's effect.
//!
//! # Operation Semantics
//!
//! | Operation    | C Macro (OP / RET)           | Returns | Rust Mapping              |
//! |-------------|------------------------------|---------|---------------------------|
//! | exchange    | `value` / `cmp`              | OLD     | `swap()`                  |
//! | `add_fetch`   | `cmp + value` / `xchg`       | NEW     | `fetch_add()` + wrapping  |
//! | `sub_fetch`   | `cmp - value` / `xchg`       | NEW     | `fetch_sub()` + wrapping  |
//! | `and_fetch`   | `cmp & value` / `xchg`       | NEW     | `fetch_and()` + bitwise   |
//! | `or_fetch`    | `cmp \| value` / `xchg`      | NEW     | `fetch_or()` + bitwise    |
//! | `xor_fetch`   | `cmp ^ value` / `xchg`       | NEW     | `fetch_xor()` + bitwise   |
//! | `nand_fetch`  | `~(cmp & value)` / `xchg`    | NEW     | `fetch_nand()` + bitwise  |
//! | `fetch_add`   | `cmp + value` / `cmp`        | OLD     | `fetch_add()`             |
//! | `fetch_sub`   | `cmp - value` / `cmp`        | OLD     | `fetch_sub()`             |
//! | `fetch_and`   | `cmp & value` / `cmp`        | OLD     | `fetch_and()`             |
//! | `fetch_or`    | `cmp \| value` / `cmp`       | OLD     | `fetch_or()`              |
//! | `fetch_xor`   | `cmp ^ value` / `cmp`        | OLD     | `fetch_xor()`             |
//! | `fetch_nand`  | `~(cmp & value)` / `cmp`     | OLD     | `fetch_nand()`            |
//!
//! # Safety
//!
//! No `unsafe` blocks — all operations use the safe `std::sync::atomic` API.
//! Per AAP §0.8.1: zero `unsafe` in safe code paths.

// External imports: std::sync::atomic types and Ordering enum
// Used for hardware-backed atomic instructions across 1/2/4/8-byte sizes.
use std::sync::atomic::Ordering;

// Internal import: C memory ordering constant converter from the atomic module.
// Converts C __ATOMIC_* integer constants (0-5) to Rust Ordering enum values.
use crate::runtime_lib::atomic::c_memorder_to_rust;

// ============================================================================
// Atomic operation enum
// ============================================================================

/// Enum representing the 13 C11 atomic read-modify-write operations.
///
/// C equivalent: The 13 `ATOMIC_*` macro variants generated by `ATOMIC_GEN`
/// in `lib/stdatomic.c` (lines 57–70).
///
/// Each variant corresponds to one of the `__atomic_*` builtins that GCC and
/// TCC provide. The `*Fetch` variants return the **new** value (after the
/// operation), while the `Fetch*` variants return the **old** value (before
/// the operation). `Exchange` always returns the old value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum AtomicOp {
    /// Atomic exchange — stores new value, returns old value.
    /// C: `__atomic_exchange_N`
    Exchange,
    /// Atomic add returning **new** value.
    /// C: `__atomic_add_fetch_N`
    AddFetch,
    /// Atomic subtract returning **new** value.
    /// C: `__atomic_sub_fetch_N`
    SubFetch,
    /// Atomic bitwise AND returning **new** value.
    /// C: `__atomic_and_fetch_N`
    AndFetch,
    /// Atomic bitwise OR returning **new** value.
    /// C: `__atomic_or_fetch_N`
    OrFetch,
    /// Atomic bitwise XOR returning **new** value.
    /// C: `__atomic_xor_fetch_N`
    XorFetch,
    /// Atomic bitwise NAND returning **new** value.
    /// C: `__atomic_nand_fetch_N` — computes `~(old & value)`
    NandFetch,
    /// Atomic add returning **old** value.
    /// C: `__atomic_fetch_add_N`
    FetchAdd,
    /// Atomic subtract returning **old** value.
    /// C: `__atomic_fetch_sub_N`
    FetchSub,
    /// Atomic bitwise AND returning **old** value.
    /// C: `__atomic_fetch_and_N`
    FetchAnd,
    /// Atomic bitwise OR returning **old** value.
    /// C: `__atomic_fetch_or_N`
    FetchOr,
    /// Atomic bitwise XOR returning **old** value.
    /// C: `__atomic_fetch_xor_N`
    FetchXor,
    /// Atomic bitwise NAND returning **old** value.
    /// C: `__atomic_fetch_nand_N` — computes `~(old & value)`, returns old
    FetchNand,
}

// ============================================================================
// Convenience re-export of memory ordering conversion
// ============================================================================

/// Converts a C `__ATOMIC_*` memory ordering constant (integer 0–5) to a Rust
/// [`Ordering`] value suitable for passing to the atomic operation functions in
/// this module.
///
/// This delegates to [`crate::runtime_lib::atomic::c_memorder_to_rust`].
///
/// # C Constants
///
/// | Constant           | Value | Rust Equivalent     |
/// |--------------------|-------|---------------------|
/// | `__ATOMIC_RELAXED` |   0   | `Ordering::Relaxed` |
/// | `__ATOMIC_CONSUME` |   1   | `Ordering::Acquire` |
/// | `__ATOMIC_ACQUIRE` |   2   | `Ordering::Acquire` |
/// | `__ATOMIC_RELEASE` |   3   | `Ordering::Release` |
/// | `__ATOMIC_ACQ_REL` |   4   | `Ordering::AcqRel`  |
/// | `__ATOMIC_SEQ_CST` |   5   | `Ordering::SeqCst`  |
///
/// Out-of-range values default to `SeqCst` (strongest ordering) for safety.
#[inline]
pub(crate) fn convert_c_memorder(memorder: i32) -> Ordering {
    c_memorder_to_rust(memorder)
}

// ============================================================================
// Macro for generating atomic operation modules per data width
// ============================================================================

/// Generates a module containing all 13 C11 atomic operations for a given
/// atomic type and value width.
///
/// The generated module mirrors the C expansion of `ATOMIC_GEN(TYPE, SIZE)`
/// at `lib/stdatomic.c` lines 57–75:
///
/// ```text
/// ATOMIC_GEN(uint8_t, 1)   →  ops_1 module
/// ATOMIC_GEN(uint16_t, 2)  →  ops_2 module
/// ATOMIC_GEN(uint32_t, 4)  →  ops_4 module
/// ATOMIC_GEN(uint64_t, 8)  →  ops_8 module
/// ```
macro_rules! define_atomic_ops {
    (
        $mod_name:ident,
        $atomic_ty:ident,
        $val_ty:ty,
        $size:literal,
        $c_type:expr
    ) => {
        #[doc = concat!(
            "Atomic operations for `", stringify!($val_ty), "` values (",
            stringify!($size), "-byte width).\n\n",
            "C equivalent: `ATOMIC_GEN(", $c_type, ", ", stringify!($size),
            ")` expansion in `lib/stdatomic.c` (line 72–75).\n\n",
            "Each function performs one of the 13 C11 atomic read-modify-write\n",
            "operations using `std::sync::atomic::", stringify!($atomic_ty),
            "` hardware-backed methods."
        )]
        pub(crate) mod $mod_name {
            use std::sync::atomic::{$atomic_ty, Ordering};

            /// Atomic exchange — atomically stores `value` and returns the
            /// previous value.
            ///
            /// C equivalent: `__atomic_exchange_N(volatile void *atom, T value, int memorder)`
            /// where N = size suffix. Uses CAS loop: `OP = value`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn exchange(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.swap(value, order)
            }

            /// Atomic add returning the **new** value (after addition).
            ///
            /// C equivalent: `__atomic_add_fetch_N` — `OP = (cmp + value)`, `RET = xchg` (new).
            /// Wrapping arithmetic matches C unsigned overflow semantics.
            #[inline]
            pub(crate) fn add_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_add(value, order).wrapping_add(value)
            }

            /// Atomic subtract returning the **new** value (after subtraction).
            ///
            /// C equivalent: `__atomic_sub_fetch_N` — `OP = (cmp - value)`, `RET = xchg` (new).
            /// Wrapping arithmetic matches C unsigned underflow semantics.
            #[inline]
            pub(crate) fn sub_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_sub(value, order).wrapping_sub(value)
            }

            /// Atomic bitwise AND returning the **new** value.
            ///
            /// C equivalent: `__atomic_and_fetch_N` — `OP = (cmp & value)`, `RET = xchg` (new).
            #[inline]
            pub(crate) fn and_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_and(value, order) & value
            }

            /// Atomic bitwise OR returning the **new** value.
            ///
            /// C equivalent: `__atomic_or_fetch_N` — `OP = (cmp | value)`, `RET = xchg` (new).
            #[inline]
            pub(crate) fn or_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_or(value, order) | value
            }

            /// Atomic bitwise XOR returning the **new** value.
            ///
            /// C equivalent: `__atomic_xor_fetch_N` — `OP = (cmp ^ value)`, `RET = xchg` (new).
            #[inline]
            pub(crate) fn xor_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_xor(value, order) ^ value
            }

            /// Atomic bitwise NAND returning the **new** value.
            ///
            /// C equivalent: `__atomic_nand_fetch_N` — `OP = ~(cmp & value)`, `RET = xchg` (new).
            /// NAND semantics: `!(old & value)` — bitwise NOT of (old AND value),
            /// matching the C expression `~(cmp & value)`.
            #[inline]
            pub(crate) fn nand_fetch(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                let old = atom.fetch_nand(value, order);
                !(old & value)
            }

            /// Atomic add returning the **old** value (before addition).
            ///
            /// C equivalent: `__atomic_fetch_add_N` — `OP = (cmp + value)`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn fetch_add(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_add(value, order)
            }

            /// Atomic subtract returning the **old** value (before subtraction).
            ///
            /// C equivalent: `__atomic_fetch_sub_N` — `OP = (cmp - value)`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn fetch_sub(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_sub(value, order)
            }

            /// Atomic bitwise AND returning the **old** value.
            ///
            /// C equivalent: `__atomic_fetch_and_N` — `OP = (cmp & value)`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn fetch_and(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_and(value, order)
            }

            /// Atomic bitwise OR returning the **old** value.
            ///
            /// C equivalent: `__atomic_fetch_or_N` — `OP = (cmp | value)`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn fetch_or(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_or(value, order)
            }

            /// Atomic bitwise XOR returning the **old** value.
            ///
            /// C equivalent: `__atomic_fetch_xor_N` — `OP = (cmp ^ value)`, `RET = cmp` (old).
            #[inline]
            pub(crate) fn fetch_xor(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_xor(value, order)
            }

            /// Atomic bitwise NAND returning the **old** value.
            ///
            /// C equivalent: `__atomic_fetch_nand_N` — `OP = ~(cmp & value)`, `RET = cmp` (old).
            /// The NAND is applied atomically; this function returns the value that
            /// was present *before* the NAND was stored.
            #[inline]
            pub(crate) fn fetch_nand(
                atom: &$atomic_ty,
                value: $val_ty,
                order: Ordering,
            ) -> $val_ty {
                atom.fetch_nand(value, order)
            }
        }
    };
}

// ============================================================================
// Atomic operation modules — one per data width
// ============================================================================

// C: ATOMIC_GEN(uint8_t, 1)  — lib/stdatomic.c line 72
define_atomic_ops!(ops_1, AtomicU8, u8, 1, "uint8_t");

// C: ATOMIC_GEN(uint16_t, 2) — lib/stdatomic.c line 73
define_atomic_ops!(ops_2, AtomicU16, u16, 2, "uint16_t");

// C: ATOMIC_GEN(uint32_t, 4) — lib/stdatomic.c line 74
define_atomic_ops!(ops_4, AtomicU32, u32, 4, "uint32_t");

// C: ATOMIC_GEN(uint64_t, 8) — lib/stdatomic.c line 75
define_atomic_ops!(ops_8, AtomicU64, u64, 8, "uint64_t");

// ============================================================================
// Lock-free query
// ============================================================================

/// Determines whether atomic operations for a given byte size are lock-free
/// on the current architecture.
///
/// C equivalent: `__atomic_is_lock_free(unsigned long size, const volatile void *ptr)`
/// at `lib/stdatomic.c` lines 84–100.
///
/// # Lock-Free Guarantees
///
/// | Size | 32-bit (i386/ARM) | 64-bit (x86_64/AArch64/RISC-V) |
/// |------|-------------------|---------------------------------|
/// |  1   | ✓ lock-free       | ✓ lock-free                     |
/// |  2   | ✓ lock-free       | ✓ lock-free                     |
/// |  4   | ✓ lock-free       | ✓ lock-free                     |
/// |  8   | ✗ NOT lock-free   | ✓ lock-free                     |
/// | >8   | ✗ NOT lock-free   | ✗ NOT lock-free                 |
///
/// On 32-bit architectures, 8-byte atomics require locking (e.g., i386 uses
/// `lock cmpxchg8b` which is lock-free but only for compare-exchange, not for
/// general-purpose atomic operations without CAS loops).
///
/// The `ptr` parameter from the C API is not needed in Rust — alignment is
/// guaranteed by the type system for `std::sync::atomic` types.
///
/// # Architecture Detection
///
/// Uses `cfg!()` macro for compile-time architecture detection, matching the
/// C preprocessor guards:
/// ```c
/// #if defined __x86_64__ || defined __aarch64__ || defined __riscv
///     case 8: ret = true; break;
/// #else
///     case 8: ret = false; break;
/// #endif
/// ```
pub(crate) fn is_lock_free(size: usize) -> bool {
    match size {
        1 | 2 | 4 => true,
        8 => {
            // 8-byte atomics are lock-free only on 64-bit architectures.
            // C: `#if defined __x86_64__ || defined __aarch64__ || defined __riscv`
            cfg!(any(
                target_arch = "x86_64",
                target_arch = "aarch64",
                target_arch = "riscv64"
            ))
        }
        _ => false,
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU8, AtomicU16, AtomicU32, AtomicU64, Ordering};

    /// Verify all 13 operations produce correct results for 1-byte atomics.
    #[test]
    fn test_ops_1_all_operations() {
        let atom = AtomicU8::new(10);

        // exchange: stores 20, returns old (10)
        assert_eq!(ops_1::exchange(&atom, 20, Ordering::SeqCst), 10);
        assert_eq!(atom.load(Ordering::SeqCst), 20);

        // fetch_add: adds 5, returns old (20)
        assert_eq!(ops_1::fetch_add(&atom, 5, Ordering::SeqCst), 20);
        assert_eq!(atom.load(Ordering::SeqCst), 25);

        // add_fetch: adds 5, returns new (30)
        assert_eq!(ops_1::add_fetch(&atom, 5, Ordering::SeqCst), 30);
        assert_eq!(atom.load(Ordering::SeqCst), 30);

        // fetch_sub: subs 10, returns old (30)
        assert_eq!(ops_1::fetch_sub(&atom, 10, Ordering::SeqCst), 30);
        assert_eq!(atom.load(Ordering::SeqCst), 20);

        // sub_fetch: subs 5, returns new (15)
        assert_eq!(ops_1::sub_fetch(&atom, 5, Ordering::SeqCst), 15);
        assert_eq!(atom.load(Ordering::SeqCst), 15);

        // fetch_and: AND with 0x0F, returns old (15 = 0x0F)
        atom.store(0xAB, Ordering::SeqCst);
        assert_eq!(ops_1::fetch_and(&atom, 0x0F, Ordering::SeqCst), 0xAB);
        assert_eq!(atom.load(Ordering::SeqCst), 0x0B);

        // and_fetch: AND with 0xFF, returns new (0x0B)
        assert_eq!(ops_1::and_fetch(&atom, 0xFF, Ordering::SeqCst), 0x0B);
        assert_eq!(atom.load(Ordering::SeqCst), 0x0B);

        // fetch_or: OR with 0xF0, returns old (0x0B)
        assert_eq!(ops_1::fetch_or(&atom, 0xF0, Ordering::SeqCst), 0x0B);
        assert_eq!(atom.load(Ordering::SeqCst), 0xFB);

        // or_fetch: OR with 0x04, returns new (0xFF)
        assert_eq!(ops_1::or_fetch(&atom, 0x04, Ordering::SeqCst), 0xFF);
        assert_eq!(atom.load(Ordering::SeqCst), 0xFF);

        // fetch_xor: XOR with 0xFF, returns old (0xFF)
        assert_eq!(ops_1::fetch_xor(&atom, 0xFF, Ordering::SeqCst), 0xFF);
        assert_eq!(atom.load(Ordering::SeqCst), 0x00);

        // xor_fetch: XOR with 0xAA, returns new (0xAA)
        assert_eq!(ops_1::xor_fetch(&atom, 0xAA, Ordering::SeqCst), 0xAA);
        assert_eq!(atom.load(Ordering::SeqCst), 0xAA);

        // fetch_nand: NAND(0xAA, 0xFF) → old=0xAA, new=!(0xAA & 0xFF)=!0xAA=0x55
        assert_eq!(ops_1::fetch_nand(&atom, 0xFF, Ordering::SeqCst), 0xAA);
        assert_eq!(atom.load(Ordering::SeqCst), 0x55);

        // nand_fetch: NAND(0x55, 0x0F) → new=!(0x55 & 0x0F)=!(0x05)=0xFA
        assert_eq!(ops_1::nand_fetch(&atom, 0x0F, Ordering::SeqCst), 0xFA);
        assert_eq!(atom.load(Ordering::SeqCst), 0xFA);
    }

    /// Verify operations work correctly for 2-byte atomics.
    #[test]
    fn test_ops_2_basic() {
        let atom = AtomicU16::new(1000);

        assert_eq!(ops_2::exchange(&atom, 2000, Ordering::SeqCst), 1000);
        assert_eq!(ops_2::add_fetch(&atom, 500, Ordering::SeqCst), 2500);
        assert_eq!(ops_2::sub_fetch(&atom, 100, Ordering::SeqCst), 2400);
        assert_eq!(ops_2::fetch_add(&atom, 100, Ordering::SeqCst), 2400);
        assert_eq!(ops_2::fetch_sub(&atom, 50, Ordering::SeqCst), 2500);

        atom.store(0xFF00, Ordering::SeqCst);
        assert_eq!(ops_2::and_fetch(&atom, 0x0FF0, Ordering::SeqCst), 0x0F00);
        assert_eq!(ops_2::or_fetch(&atom, 0x000F, Ordering::SeqCst), 0x0F0F);
        assert_eq!(ops_2::xor_fetch(&atom, 0xFFFF, Ordering::SeqCst), 0xF0F0);

        assert_eq!(ops_2::fetch_and(&atom, 0xFFFF, Ordering::SeqCst), 0xF0F0);
        assert_eq!(ops_2::fetch_or(&atom, 0x0000, Ordering::SeqCst), 0xF0F0);
        assert_eq!(ops_2::fetch_xor(&atom, 0x0000, Ordering::SeqCst), 0xF0F0);

        assert_eq!(ops_2::fetch_nand(&atom, 0xFFFF, Ordering::SeqCst), 0xF0F0);
        assert_eq!(atom.load(Ordering::SeqCst), 0x0F0F);
        assert_eq!(ops_2::nand_fetch(&atom, 0x00FF, Ordering::SeqCst), 0xFFF0);
    }

    /// Verify operations work correctly for 4-byte atomics.
    #[test]
    fn test_ops_4_basic() {
        let atom = AtomicU32::new(100_000);

        assert_eq!(ops_4::exchange(&atom, 200_000, Ordering::SeqCst), 100_000);
        assert_eq!(ops_4::add_fetch(&atom, 50_000, Ordering::SeqCst), 250_000);
        assert_eq!(ops_4::fetch_sub(&atom, 25_000, Ordering::SeqCst), 250_000);
        assert_eq!(atom.load(Ordering::SeqCst), 225_000);

        atom.store(0xDEAD_BEEF, Ordering::SeqCst);
        assert_eq!(ops_4::fetch_and(&atom, 0xFFFF_0000, Ordering::SeqCst), 0xDEAD_BEEF);
        assert_eq!(atom.load(Ordering::SeqCst), 0xDEAD_0000);

        assert_eq!(ops_4::fetch_nand(&atom, 0xFFFF_FFFF, Ordering::SeqCst), 0xDEAD_0000);
        assert_eq!(atom.load(Ordering::SeqCst), !0xDEAD_0000);

        atom.store(0x1234_5678, Ordering::SeqCst);
        assert_eq!(ops_4::nand_fetch(&atom, 0x0000_FFFF, Ordering::SeqCst), !(0x1234_5678 & 0x0000_FFFF));
    }

    /// Verify operations work correctly for 8-byte atomics.
    #[test]
    fn test_ops_8_basic() {
        let atom = AtomicU64::new(1_000_000_000);

        assert_eq!(ops_8::exchange(&atom, 2_000_000_000, Ordering::SeqCst), 1_000_000_000);
        assert_eq!(ops_8::add_fetch(&atom, 500, Ordering::SeqCst), 2_000_000_500);
        assert_eq!(ops_8::fetch_add(&atom, 500, Ordering::SeqCst), 2_000_000_500);
        assert_eq!(ops_8::sub_fetch(&atom, 1000, Ordering::SeqCst), 2_000_000_000);

        atom.store(0xDEAD_BEEF_CAFE_BABE, Ordering::SeqCst);
        assert_eq!(
            ops_8::fetch_and(&atom, 0xFFFF_FFFF_0000_0000, Ordering::SeqCst),
            0xDEAD_BEEF_CAFE_BABE
        );
        assert_eq!(atom.load(Ordering::SeqCst), 0xDEAD_BEEF_0000_0000);

        assert_eq!(
            ops_8::fetch_nand(&atom, 0xFFFF_FFFF_FFFF_FFFF, Ordering::SeqCst),
            0xDEAD_BEEF_0000_0000
        );
        assert_eq!(atom.load(Ordering::SeqCst), !0xDEAD_BEEF_0000_0000);
    }

    /// Verify wrapping arithmetic on overflow/underflow boundaries.
    #[test]
    fn test_wrapping_arithmetic() {
        // u8 overflow: 255 + 1 = 0 (wrapping)
        let atom8 = AtomicU8::new(255);
        assert_eq!(ops_1::add_fetch(&atom8, 1, Ordering::SeqCst), 0);
        assert_eq!(atom8.load(Ordering::SeqCst), 0);

        // u8 underflow: 0 - 1 = 255 (wrapping)
        assert_eq!(ops_1::sub_fetch(&atom8, 1, Ordering::SeqCst), 255);
        assert_eq!(atom8.load(Ordering::SeqCst), 255);

        // u16 overflow
        let atom16 = AtomicU16::new(u16::MAX);
        assert_eq!(ops_2::add_fetch(&atom16, 1, Ordering::SeqCst), 0);

        // u32 overflow
        let atom32 = AtomicU32::new(u32::MAX);
        assert_eq!(ops_4::add_fetch(&atom32, 1, Ordering::SeqCst), 0);

        // u64 overflow
        let atom64 = AtomicU64::new(u64::MAX);
        assert_eq!(ops_8::add_fetch(&atom64, 1, Ordering::SeqCst), 0);
    }

    /// Verify NAND semantics: `!(old & value)` matching C `~(cmp & value)`.
    #[test]
    fn test_nand_semantics() {
        // For u8: NAND(0xFF, 0xAA) = !(0xFF & 0xAA) = !(0xAA) = 0x55
        let atom = AtomicU8::new(0xFF);
        assert_eq!(ops_1::nand_fetch(&atom, 0xAA, Ordering::SeqCst), 0x55);
        assert_eq!(atom.load(Ordering::SeqCst), 0x55);

        // fetch_nand returns OLD, atom gets new value
        let atom = AtomicU8::new(0xFF);
        assert_eq!(ops_1::fetch_nand(&atom, 0xAA, Ordering::SeqCst), 0xFF);
        assert_eq!(atom.load(Ordering::SeqCst), 0x55);

        // NAND with 0x00: !(x & 0) = !(0) = all ones
        let atom32 = AtomicU32::new(0x1234_5678);
        assert_eq!(ops_4::nand_fetch(&atom32, 0x0000_0000, Ordering::SeqCst), 0xFFFF_FFFF);

        // NAND with all ones: !(x & 0xFFFFFFFF) = !x
        let atom32 = AtomicU32::new(0xDEAD_BEEF);
        assert_eq!(ops_4::nand_fetch(&atom32, 0xFFFF_FFFF, Ordering::SeqCst), !0xDEAD_BEEF);
    }

    /// Verify `is_lock_free` for various sizes.
    #[test]
    fn test_is_lock_free() {
        // Sizes 1, 2, 4 are always lock-free
        assert!(is_lock_free(1));
        assert!(is_lock_free(2));
        assert!(is_lock_free(4));

        // Size 8 depends on architecture
        #[cfg(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "riscv64"))]
        assert!(is_lock_free(8));

        #[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "riscv64")))]
        assert!(!is_lock_free(8));

        // Other sizes are never lock-free
        assert!(!is_lock_free(0));
        assert!(!is_lock_free(3));
        assert!(!is_lock_free(5));
        assert!(!is_lock_free(16));
        assert!(!is_lock_free(32));
        assert!(!is_lock_free(usize::MAX));
    }

    /// Verify `convert_c_memorder` delegates correctly to `c_memorder_to_rust`.
    #[test]
    fn test_convert_c_memorder() {
        assert_eq!(convert_c_memorder(0), Ordering::Relaxed);
        assert_eq!(convert_c_memorder(1), Ordering::Acquire); // Consume → Acquire
        assert_eq!(convert_c_memorder(2), Ordering::Acquire);
        assert_eq!(convert_c_memorder(3), Ordering::Release);
        assert_eq!(convert_c_memorder(4), Ordering::AcqRel);
        assert_eq!(convert_c_memorder(5), Ordering::SeqCst);
        // Out-of-range defaults to SeqCst
        assert_eq!(convert_c_memorder(6), Ordering::SeqCst);
        assert_eq!(convert_c_memorder(-1), Ordering::SeqCst);
    }

    /// Verify `AtomicOp` enum has all 13 variants and they are distinct.
    #[test]
    fn test_atomic_op_enum() {
        let ops = [
            AtomicOp::Exchange,
            AtomicOp::AddFetch,
            AtomicOp::SubFetch,
            AtomicOp::AndFetch,
            AtomicOp::OrFetch,
            AtomicOp::XorFetch,
            AtomicOp::NandFetch,
            AtomicOp::FetchAdd,
            AtomicOp::FetchSub,
            AtomicOp::FetchAnd,
            AtomicOp::FetchOr,
            AtomicOp::FetchXor,
            AtomicOp::FetchNand,
        ];

        // All 13 variants present
        assert_eq!(ops.len(), 13);

        // All distinct (no duplicates)
        for i in 0..ops.len() {
            for j in (i + 1)..ops.len() {
                assert_ne!(ops[i], ops[j], "Variants at index {i} and {j} should differ");
            }
        }

        // Debug + Clone + Copy
        let op = AtomicOp::Exchange;
        let _debug = format!("{op:?}");
        let _ = op;
        let _ = op;
    }

    /// Verify that different memory orderings work without panicking.
    #[test]
    fn test_memory_orderings() {
        let orderings = [
            Ordering::Relaxed,
            Ordering::Acquire,
            Ordering::Release,
            Ordering::AcqRel,
            Ordering::SeqCst,
        ];

        for &order in &orderings {
            let atom = AtomicU32::new(42);

            // exchange works with all orderings
            let _ = ops_4::exchange(&atom, 100, order);

            // fetch_add/sub work with all orderings
            let _ = ops_4::fetch_add(&atom, 1, order);
            let _ = ops_4::fetch_sub(&atom, 1, order);

            // bitwise ops work with all orderings
            let _ = ops_4::fetch_and(&atom, 0xFF, order);
            let _ = ops_4::fetch_or(&atom, 0x01, order);
            let _ = ops_4::fetch_xor(&atom, 0x01, order);
            let _ = ops_4::fetch_nand(&atom, 0xFF, order);
        }
    }
}
